#include <libavcodec/avcodec.h>

#define PJMEDIA_HAS_VIDEO	1
#define PJMEDIA_HAS_FFMPEG	1

#define PJMEDIA_HAS_SPEEX_CODEC 0
#define PJMEDIA_HAS_ILBC_CODEC 0
#define PJMEDIA_HAS_GSM_CODEC 0
#define PJMEDIA_HAS_G711_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 0
#define PJMEDIA_HAS_INTEL_IPP 0
#define PJMEDIA_HAS_G7221_CODEC 1
#define PJMEDIA_HAS_L16_CODEC 0
#define PJMEDIA_HAS_OPENCORE_AMRNB_CODEC 0
#define PJMEDIA_HAS_OPENCORE_AMRWB_CODEC 0
#define PJMEDIA_HAS_SILK_CODEC 0
#define PJMEDIA_HAS_OPUS_CODEC 0
#define PJMEDIA_HAS_BCG729 0

#define PJMEDIA_HAS_FFMPEG_CODEC_H263P 0

#define FF_INPUT_BUFFER_PADDING_SIZE AV_INPUT_BUFFER_PADDING_SIZE
